"""Source profiling for the DSS150P pipeline.

Reads the immutable source file (never modifies it) and writes a Markdown
profile to metadata/source_profile.md. Data-quality checks are added to this
module in a later phase.

Usage (from the project root):
    python -m src.validate --profile
"""
import argparse
import csv
import hashlib
from pathlib import Path

import pandas as pd

DEFAULT_SOURCE = "data/source/dataset.csv"
DEFAULT_OUTPUT = "metadata/source_profile.md"
TARGET = "popularity"
KEY = "track_id"
TIER_BINS = [-1, 33, 66, 100]  # Low <= 33, Mid 34-66, High > 66
TIER_LABELS = ["Low", "Mid", "High"]
UNIT_RANGE_COLUMNS = [
    "danceability", "energy", "speechiness", "acousticness",
    "instrumentalness", "liveness", "valence",
]


def sha256_of_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def md_table(headers, rows):
    lines = ["| " + " | ".join(headers) + " |",
             "| " + " | ".join("---" for _ in headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(lines)


def file_facts(path):
    raw = Path(path).read_bytes()
    try:
        raw.decode("utf-8")
        encoding = "utf-8 (decodes without errors)"
    except UnicodeDecodeError:
        encoding = "not valid utf-8"
    sample = raw[:4096].decode("utf-8", errors="replace")
    delimiter = csv.Sniffer().sniff(sample, delimiters=",;\t|").delimiter
    line_ending = "CRLF" if b"\r\n" in raw[:4096] else "LF"
    return {
        "File name": Path(path).name,
        "Location (relative)": str(Path(path).as_posix()),
        "Format": "CSV, one header row",
        "Encoding": encoding,
        "Delimiter": repr(delimiter),
        "Line endings": line_ending,
        "Size (bytes)": f"{len(raw):,}",
        "SHA-256": sha256_of_file(path),
    }


def column_profile(df):
    rows = []
    for column in df.columns:
        series = df[column]
        nulls = int(series.isna().sum())
        if pd.api.types.is_numeric_dtype(series):
            low, high = series.min(), series.max()
        else:
            low, high = "n/a", "n/a"
        rows.append([
            column, str(series.dtype), nulls,
            f"{nulls / len(df):.4%}", f"{series.nunique():,}", low, high,
        ])
    return rows


def build_profile(path):
    df = pd.read_csv(path)
    facts = file_facts(path)
    out = ["# Source Profile", "",
           "Generated by `python -m src.validate --profile`. "
           "Automatic sections only; the hand-written notes are at the end.", ""]

    out += ["## 1. File facts", "",
            md_table(["Property", "Value"], list(facts.items())), ""]

    out += ["## 2. Shape", "",
            f"- Rows: **{len(df):,}**",
            f"- Columns: **{df.shape[1]}**", ""]

    out += ["## 3. Columns", "",
            md_table(["Column", "Type", "Nulls", "Null rate",
                      "Distinct", "Min", "Max"], column_profile(df)), ""]

    candidate_keys = [c for c in df.columns if df[c].is_unique]
    dup_rows = int(df.duplicated().sum())
    dup_key = int(df.duplicated(subset=[KEY]).sum())
    dup_key_genre = int(df.duplicated(subset=[KEY, "track_genre"]).sum())
    out += ["## 4. Keys and duplicates", "",
            f"- Columns with all-unique values (candidate keys): "
            f"{', '.join(candidate_keys) if candidate_keys else 'none'}",
            f"- Fully duplicated rows: **{dup_rows:,}**",
            f"- Rows repeating an earlier `{KEY}`: **{dup_key:,}**",
            f"- Rows repeating an earlier (`{KEY}`, `track_genre`) pair: "
            f"**{dup_key_genre:,}**", ""]

    out += ["## 5. Target variable (`popularity`)", "",
            md_table(["Statistic", "Value"],
                     [[k, round(v, 3)] for k, v in
                      df[TARGET].describe().items()]), ""]
    tiers = pd.cut(df[TARGET], bins=TIER_BINS, labels=TIER_LABELS)
    counts = tiers.value_counts().reindex(TIER_LABELS)
    out += ["Tier distribution on the raw source "
            "(Low <= 33, Mid 34-66, High > 66):", "",
            md_table(["Tier", "Count", "Share"],
                     [[t, f"{int(counts[t]):,}",
                       f"{counts[t] / len(df):.1%}"] for t in TIER_LABELS]), ""]

    checks = [["popularity outside 0-100",
               int(((df[TARGET] < 0) | (df[TARGET] > 100)).sum())]]
    for column in UNIT_RANGE_COLUMNS:
        checks.append([f"{column} outside 0-1",
                       int(((df[column] < 0) | (df[column] > 1)).sum())])
    checks.append(["tempo equal to 0", int((df["tempo"] == 0).sum())])
    checks.append(["time_signature equal to 0",
                   int((df["time_signature"] == 0).sum())])
    out += ["## 6. Range and malformed-value checks", "",
            md_table(["Check", "Rows affected"], checks), ""]

    cleaned = df.dropna(subset=["artists", "album_name", "track_name"])
    cleaned = cleaned.drop_duplicates(subset=[KEY], keep="first")
    c_tiers = pd.cut(cleaned[TARGET], bins=TIER_BINS, labels=TIER_LABELS)
    c_counts = c_tiers.value_counts().reindex(TIER_LABELS)
    out += ["## 7. Cross-check against the group's baseline cleaning", "",
            "Baseline rule: drop rows with null artists/album_name/track_name, "
            f"then drop repeated `{KEY}` keeping the first.", "",
            f"- Rows after cleaning: **{len(cleaned):,}** "
            "(the group report states 89,740)",
            f"- Tier counts after cleaning: Low {int(c_counts['Low']):,}, "
            f"Mid {int(c_counts['Mid']):,}, High {int(c_counts['High']):,} "
            "(the report's Table I states 45,159 / 40,061 / 4,520)", ""]
    return "\n".join(out)


NOTES_MARKER = "<!-- HAND-WRITTEN NOTES BELOW: kept when the profile is regenerated -->"
DEFAULT_NOTES = "\n\n## 8. Hand-written notes\n\n(To be completed.)\n"


def existing_notes(path):
    """Return the hand-written text below the marker, if the file has one."""
    target = Path(path)
    if target.exists():
        text = target.read_text(encoding="utf-8")
        if NOTES_MARKER in text:
            return text.split(NOTES_MARKER, 1)[1]
    return DEFAULT_NOTES


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", action="store_true",
                        help="write the source profile")
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if not args.profile:
        parser.print_help()
        return
    notes = existing_notes(args.output)
    text = build_profile(args.source) + "\n" + NOTES_MARKER + notes
    Path(args.output).write_text(text, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()